# Preprocesamiento de Datos en Scikit-Learn 1
Dado el siguiente conjunto de datos, utiliza `MinMaxScaler` de Scikit-Learn para normalizar los datos en un rango de 0 a 1.
```
# Datos originales
datos = np.array([[5, 15, 25],
                 [10, 20, 30],
                 [15, 25, 35]])
```
Convierte los datos originales para que estén en el rango de 0 a 1 utilizando `MinMaxScaler` y guarda el resultado en una variable llamada `datos_normalizados`.

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler


# Datos originales
datos = np.array([[5, 15, 25],
                 [10, 20, 30],
                 [15, 25, 35]])

# Normalización
scaler = MinMaxScaler(feature_range=(0, 1))
datos_normalizados = scaler.fit_transform(datos)
datos_normalizados

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

# Preprocesamiento de Datos en Scikit-Learn 2
Usa `StandardScaler` de Scikit-Learn para estandarizar el siguiente conjunto de datos, de manera que cada característica tenga una media de 0 y una desviación estándar de 1.
```
# Datos originales
datos = np.array([[10, 2000, 30000],
                 [15, 3000, 50000],
                 [20, 4000, 70000]])
```
Convierte los datos originales para que cada característica tenga una media de 0 y una desviación estándar de 1 utilizando `StandardScaler` y guarda el resultado en una variable llamada `datos_estandardizados`.

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler


# Datos originales
datos = np.array([[10, 2000, 30000],
                 [15, 3000, 50000],
                 [20, 4000, 70000]])

# Normalización
scaler = StandardScaler()
datos_estandardizados = scaler.fit_transform(datos)
datos_estandardizados

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

# Preprocesamiento de Datos en Scikit-Learn 3
Usa `OneHotEncoder` de Scikit-Learn para transformar las características categóricas del siguiente conjunto de datos.
```
# Datos originales
datos = np.array([['Rojo', 'Pequeño', 'Cítrico'],
                 ['Verde', 'Mediano', 'Dulce'],
                 ['Amarillo', 'Grande', 'Cítrico']])
```
Convierte los datos originales utilizando `OneHotEncoder` y guarda el resultado en una variable llamada `datos_codificados`.

In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder


# Datos originales
datos = np.array([['Rojo', 'Pequeño', 'Cítrico'],
                 ['Verde', 'Mediano', 'Dulce'],
                 ['Amarillo', 'Grande', 'Cítrico']])

# Normalización
encoder = OneHotEncoder(sparse_output=False)  # en Udemy, es solo sparse
datos_codificados = encoder.fit_transform(datos)
datos_codificados

array([[0., 1., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0.]])