# Forma y Estructura de los Arrays de NumPy 1

Crea un array de NumPy llamado `array_original` que contenga los números del 1 al 12 y luego cambia su forma para que se convierta en un array de 3 filas y 4 columnas. Almacenalo en una variable llamada `array_reshape`

In [2]:
import numpy as np


array_original: np.ndarray = np.array(range(1, 13))
array_reshape: np.ndarray = array_original.reshape(3, 4)
print(array_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Forma y Estructura de los Arrays de NumPy 2

Crea un array bidimensional llamado: `array_original` de forma (2, 3) que contenga los primeros 6 números enteros positivos. Utiliza el método correcto para cambiar sus filas por columnas. Almacenalo en una variable llamada `array_modificado`

In [3]:
import numpy as np


array_original: np.ndarray = np.array([[1, 2, 3], [4, 5, 6]])
array_modificado: np.ndarray = array_original.transpose()
print(array_modificado)

[[1 4]
 [2 5]
 [3 6]]


# Forma y Estructura de los Arrays de NumPy 3

Crea un array de 2 dimensiones `array_original` de forma (2, 3) que contenga los primeros 6 números enteros positivos. Identico al del ejercicio anterior. Luego, crea una copia aplanada de este array y almacénalo en una variable llamada `array_aplanado`



In [4]:
import numpy as np


array_original: np.ndarray = np.array([[1, 2, 3], [4, 5, 6]])
array_aplanado: np.ndarray = array_original.flatten()
print(array_aplanado)

[1 2 3 4 5 6]
