# Forma y Estructura de los Arrays de NumPy 1

Crea un array de NumPy llamado `array_original` que contenga los números del 1 al 12 y luego cambia su forma para que se convierta en un array de 3 filas y 4 columnas. Almacenalo en una variable llamada `array_reshape`

In [2]:
import numpy as np


array_original: np.ndarray = np.array(range(1, 13))
array_reshape: np.ndarray = array_original.reshape(3, 4)
print(array_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
