# Operaciones Avanzadas y Funciones Universales en NumPy

In [1]:
import numpy as np

In [2]:
array1: np.ndarray = np.array([1, 2, 3])
print(array1)

[1 2 3]


In [3]:
array2: np.ndarray = np.array([[0], [10], [20], [30]])
print(array2)

[[ 0]
 [10]
 [20]
 [30]]


In [4]:
# Sumar arrays con formas distintas
sum_arrays: np.ndarray = array1 + array2
print(sum_arrays)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [5]:
# Restar arrays con formas distintas
sub_arrays: np.ndarray = array1 - array2
print(sub_arrays)

[[  1   2   3]
 [ -9  -8  -7]
 [-19 -18 -17]
 [-29 -28 -27]]


In [6]:
# Multiplicar arrays con formas distintas
mult_arrays: np.ndarray = array1 * array2
print(mult_arrays)

[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


### Funciones universales

In [7]:
# Definir arrays 1D de ejemplo
a: np.ndarray = np.array([1, 2, 3])
b: np.ndarray = np.array([4, 5, 6])
print(f'{a=}')
print(f'{b=}')

a=array([1, 2, 3])
b=array([4, 5, 6])


In [8]:
# Sumar
result = np.add(a, b)
print(result)

[5 7 9]


In [9]:
# Restar
result = np.subtract(a, b)
print(result)

[-3 -3 -3]


In [10]:
# Multiplicar
result = np.multiply(a, b)
print(result)

[ 4 10 18]


In [11]:
# Dividir
result = np.divide(a, b)
print(result)

[0.25 0.4  0.5 ]


In [16]:
# Potenciar
result = np.power(a, b)
print(result)

[  1  32 729]


In [17]:
# Calcular el exponencial
result = np.exp(a)
print(result)

[ 2.71828183  7.3890561  20.08553692]


In [18]:
# Obtener el logaritmo natural (base e)
result = np.log(a)
print(result)

[0.         0.69314718 1.09861229]


In [19]:
# Obtener el logaritmo binario (base 2)
result = np.log2(a)
print(result)

[0.        1.        1.5849625]


In [20]:
# Obtener el logaritmo decimal (base 10)
result = np.log10(a)
print(result)

[0.         0.30103    0.47712125]


In [22]:
# Obtener la raíz cuadrada
result = np.sqrt(a)
print(result)

[1.         1.41421356 1.73205081]
