# Forma y Estructura de los Arrays de NumPy

In [1]:
import numpy as np

In [3]:
array: np.ndarray = np.array(range(1, 10))
print('Array:', array)
print('Array shape:', array.shape)

Array: [1 2 3 4 5 6 7 8 9]
Array shape: (9,)


In [5]:
# Modificar array con reshape
array_reshaped: np.ndarray = array.reshape(3, 3)
print('Reshaped array:\n', array_reshaped)

Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Transponer array
array_transposed: np.ndarray = array_reshaped.transpose()
print('Transposed array:\n', array_transposed)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
# Achatar array (2D a 1D)
array_flattened: np.ndarray = array_reshaped.flatten()
print('Flattened array:', array_flattened)

Flattened array: [1 2 3 4 5 6 7 8 9]


In [ ]:
# Crear vista achatada (1D a 2D) - no ocupa memoria como flatten
array_ravel: np.ndarray = array_reshaped.ravel()
print('Array ravel:\n', array_ravel)
print('Array ravel shape:', array_ravel.shape)