# Indexación y Segmentación en Arrays de NumPy

In [1]:
import numpy as np

In [2]:
array_1d: np.ndarray = np.array(range(1, 6))
print(array_1d)

[1 2 3 4 5]


In [3]:
array_2d: np.ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Acceder al primer elemento del array_1d
print(array_1d[0])

1


In [5]:
# Acceder al último elemento del array_1d
print(array_1d[-1])

5


In [6]:
# Acceder al primer conjunto del array_2d
print(array_2d[0])

[1 2 3]


In [8]:
# Acceder a un solo elemento del array_2d (e.g. el 6)
print(array_2d[1][2])  # forma 1
print(array_2d[1, 2])  # forma 2

6
6


In [9]:
# Aplicar slicing al array_1d
print(array_1d[1:4])

[2 3 4]


In [10]:
# Aplicar slicing al array_2d (e.g. la segunda fila)
print(array_2d[1, :])

[4 5 6]


In [12]:
# Aplicar slicing al array_2d (e.g. los últimos 2 elementos)
print(array_2d[2, 1:3])

[8 9]


In [13]:
# Aplicar slicing al array_2d (e.g. obtener una columna completa)
print(array_2d[:, 1])

[2 5 8]


In [14]:
# Aplicar slicing al array_2d
# (e.g. los 2 primeros números de las primeras 2 filas)
print(array_2d[:2, :2])

[[1 2]
 [4 5]]


In [15]:
# Indexación booleana al array_1d
print(array_1d > 3)

[False False False  True  True]


In [16]:
# Indexación booleana al array_2d (e.g. True si es par)
print(array_2d % 2 == 0)

[[False  True False]
 [ True False  True]
 [False  True False]]
