# Manipulación de Arrays en NumPy

In [1]:
import numpy as np

In [2]:
# Concatenar listas en un array
x: list[int] = [1, 2, 3]
y: list[int] = [4, 5, 6]
z: list[int] = [7, 8, 9]

print(np.concatenate([x, y, z]))

[1 2 3 4 5 6 7 8 9]


In [3]:
# Concatenar listas en un array 2D con axis=1 (horizontalmente)
a: list[list[int]] = [[1, 2], [3, 4]]
b: list[list[int]] = [[5, 6], [7, 8]]

print(np.concatenate([a, b], axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
# Concatenar listas en un array 2D con axis=0 (verticalmente)
print(np.concatenate([a, b], axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# Conocer la forma del último array concatenado
concatenated_array: np.ndarray = np.concatenate([a, b], axis=0)
print(concatenated_array.shape)

(4, 2)


In [6]:
# Redimensionar la forma del array concatenado
reshaped_array: np.ndarray = concatenated_array.reshape(2, 4)
print(reshaped_array)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
# Sumar arrays
sum_arrays_1d: np.ndarray = np.array([1, 2, 3]) + np.array([4, 5, 6])
print('1D arrays sum:\n', sum_arrays_1d)

sum_arrays_2d: np.ndarray = reshaped_array + reshaped_array
print('\n2D arrays sum:\n',sum_arrays_2d)

1D arrays sum:
 [5 7 9]

2D arrays sum:
 [[ 2  4  6  8]
 [10 12 14 16]]


In [11]:
# Multiplicar arrays
product_arrays_1d: np.ndarray = np.array([1, 2, 3]) * np.array([4, 5, 6])
print('1D arrays product:\n', product_arrays_1d)

product_arrays_2d: np.ndarray = reshaped_array * reshaped_array
print('\n2D arrays product:\n',product_arrays_2d)

1D arrays product:
 [ 4 10 18]

2D arrays product:
 [[ 1  4  9 16]
 [25 36 49 64]]


In [12]:
# Obtener las raíces cuadradas
roots_bloody_roots = np.sqrt(product_arrays_2d)
print(roots_bloody_roots)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
