# Importación y Exportación de Datos con NumPy

In [9]:
import os
import numpy as np

In [4]:
# Cargar datos desde un archivo CSV
file_path: str = './data/medallas.csv'
array: np.ndarray = np.genfromtxt(file_path, delimiter=',', skip_header=1)
print(array)

[[ nan   1.   2.   3.  nan]
 [ nan   2.   2.   4.  nan]
 [ 17.   7.  22.  46.  nan]
 [  1.   1.   5.   7.  nan]
 [ nan   3.   4.   7.  nan]
 [  2.  nan  nan   2.  nan]
 [ nan   1.  nan   1.  nan]
 [  1.   3.   3.   7.  nan]
 [  3.   1.   3.   7.  nan]
 [  1.  nan  nan   1.  nan]
 [ nan  nan   1.   1.  nan]
 [  7.   6.   8.  21.  nan]
 [  3.   1.   2.   6.  nan]
 [ nan  nan   1.   1.  nan]
 [  7.   6.  11.  24.  nan]
 [  2.   4.   6.  12.  nan]
 [ nan   4.   1.   5.  nan]
 [  3.   3.   2.   8.  nan]
 [ nan  nan   1.   1.  nan]
 [  7.   3.   5.  15.  nan]
 [  4.   4.   3.  11.  nan]
 [  3.   4.   4.  11.  nan]
 [ nan   3.   2.   5.  nan]
 [  2.   1.  nan   3.  nan]
 [  1.   1.   4.   6.  nan]
 [ 39.  41.  33. 113.  nan]
 [  1.  nan   1.   2.  nan]
 [  1.   1.   2.   4.  nan]
 [  1.  nan   1.   2.  nan]
 [ nan  nan   2.   2.  nan]
 [  1.  12.  11.  33.  nan]
 [  2.   5.   1.   8.  nan]
 [  1.  11.  16.  37.  nan]
 [ nan  nan   1.   1.  nan]
 [ 22.  21.  22.  65.  nan]
 [  2.   1.   1.   4

In [6]:
# Cargar datos desde un archivo CSV y rellenar los valores NaN con ceros
file_path: str = './data/medallas.csv'
array: np.ndarray = np.genfromtxt(
    file_path,
    delimiter=',',
    skip_header=1,
    filling_values=0
)
print(array)

[[  0.   1.   2.   3.   0.]
 [  0.   2.   2.   4.   0.]
 [ 17.   7.  22.  46.   0.]
 [  1.   1.   5.   7.   0.]
 [  0.   3.   4.   7.   0.]
 [  2.   0.   0.   2.   0.]
 [  0.   1.   0.   1.   0.]
 [  1.   3.   3.   7.   0.]
 [  3.   1.   3.   7.   0.]
 [  1.   0.   0.   1.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   6.   8.  21.   0.]
 [  3.   1.   2.   6.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   6.  11.  24.   0.]
 [  2.   4.   6.  12.   0.]
 [  0.   4.   1.   5.   0.]
 [  3.   3.   2.   8.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   3.   5.  15.   0.]
 [  4.   4.   3.  11.   0.]
 [  3.   4.   4.  11.   0.]
 [  0.   3.   2.   5.   0.]
 [  2.   1.   0.   3.   0.]
 [  1.   1.   4.   6.   0.]
 [ 39.  41.  33. 113.   0.]
 [  1.   0.   1.   2.   0.]
 [  1.   1.   2.   4.   0.]
 [  1.   0.   1.   2.   0.]
 [  0.   0.   2.   2.   0.]
 [  1.  12.  11.  33.   0.]
 [  2.   5.   1.   8.   0.]
 [  1.  11.  16.  37.   0.]
 [  0.   0.   1.   1.   0.]
 [ 22.  21.  22.  65.   0.]
 [  2.   1.   1.   4

In [7]:
"""
Cargar datos desde un archivo CSV, rellenar los valores NaN con ceros y
cambiar el tipo de dato al correcto (int).
"""
file_path: str = './data/medallas.csv'
array: np.ndarray = np.genfromtxt(
    file_path,
    delimiter=',',
    skip_header=1,
    filling_values=0,
    dtype=int
)
print(array)

[[  0   1   2   3   0]
 [  0   2   2   4   0]
 [ 17   7  22  46   0]
 [  1   1   5   7   0]
 [  0   3   4   7   0]
 [  2   0   0   2   0]
 [  0   1   0   1   0]
 [  1   3   3   7   0]
 [  3   1   3   7   0]
 [  1   0   0   1   0]
 [  0   0   1   1   0]
 [  7   6   8  21   0]
 [  3   1   2   6   0]
 [  0   0   1   1   0]
 [  7   6  11  24   0]
 [  2   4   6  12   0]
 [  0   4   1   5   0]
 [  3   3   2   8   0]
 [  0   0   1   1   0]
 [  7   3   5  15   0]
 [  4   4   3  11   0]
 [  3   4   4  11   0]
 [  0   3   2   5   0]
 [  2   1   0   3   0]
 [  1   1   4   6   0]
 [ 39  41  33 113   0]
 [  1   0   1   2   0]
 [  1   1   2   4   0]
 [  1   0   1   2   0]
 [  0   0   2   2   0]
 [  1  12  11  33   0]
 [  2   5   1   8   0]
 [  1  11  16  37   0]
 [  0   0   1   1   0]
 [ 22  21  22  65   0]
 [  2   1   1   4   0]
 [  0   0   1   1   0]
 [  0   2   3   6   0]
 [  6   7   7   2   0]
 [  1   2   4   7   0]
 [  1   1   3   5   0]
 [  2   0   2   4   0]
 [  3   2   2   7   0]
 [  2   0  

In [10]:
# Exportar un array de NumPy a un archivo CSV
file_path: str = './data/output.csv'
np.savetxt(file_path, array, delimiter=',', fmt='%d')
print('Success!') if os.path.exists(file_path) else print('Error!')

Success!
