# Integración de NumPy con Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
df: pd.DataFrame = pd.DataFrame({
    'odd': [1, 3, 5, 7],
    'even': [2, 4, 6, 8]
})

print(df)

   odd  even
0    1     2
1    3     4
2    5     6
3    7     8


In [3]:
# Convertir dataframe de pandas en array de numpy (forma 1)
arr: np.ndarray = df.to_numpy()

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
# Convertir dataframe de pandas en array de numpy (forma 2)
arr: np.ndarray = df.values

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# Convertir dataframe de pandas en array de numpy (forma 3)
arr: np.ndarray = np.array(df)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
# Aplicar aritmética de numpy a pandas (ej: raíz cuadrada)
print(np.sqrt(df))

        odd      even
0  1.000000  1.414214
1  1.732051  2.000000
2  2.236068  2.449490
3  2.645751  2.828427


In [7]:
# Devolver el valor maximo de cada una de las columnas
print(df.max())

odd     7
even    8
dtype: int64


In [8]:
# Devolver el valor maximo del dataframe con numpy
print(np.max(df))

8


In [9]:
# Crear un dataframe desde un array de numpy
df: pd.DataFrame = pd.DataFrame(arr)

print(df)

   0  1
0  1  2
1  3  4
2  5  6
3  7  8


In [10]:
# Crear un dataframe desde un array de numpy y asignando nombres a las columnas
df: pd.DataFrame = pd.DataFrame(arr, columns=['odd', 'even'])

print(df)

   odd  even
0    1     2
1    3     4
2    5     6
3    7     8
